sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 11111111
  alioss:
      endpoint: oss-ap-northeast-2.aliyuncs.com
      access-key-id: LTAI5tLhhLB57VH5jep2AcU9
      access-key-secret: J3HmEtiAJrZSpjz1DDZZyGgvNSsbGW
      bucket-name: sky-itcast-zhaotingyou
