sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 11111111
#  alioss:
#      endpoint: ${sky.alioss.endpoint}
#      access-key-id: ${sky.alioss.access-key-id}
#      access-key-secret: ${sky.alioss.access-key-secret}
#      bucket-name: ${sky.alioss.bucket-name}
