sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 11111111
  alioss:
      endpoint: oss-ap-northeast-2.aliyuncs.com
      access-key-id: LTAI5tLhhLB57VH5jep2AcU9
      access-key-secret: J3HmEtiAJrZSpjz1DDZZyGgvNSsbGW
      bucket-name: sky-itcast-zhaotingyou
  redis:
    host: localhost
    port: 6379
    password: 152367130
    database: 10
  wechat:
    appid: wx5566ab09f4fa64ac
    secret: 49dc0e1b9c95802e1b6e8871ffc81fe5
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\pay\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\pay\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://58869fb.r2.cpolar.top/notify/paySuccess
    refundNotifyUrl: https://58869fb.r2.cpolar.top/notify/refundSuccess

